theme: jekyll-theme-dinky
title: Newbie Disco
author: Jasmine Zou
email: jasmine.zou22@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Programmer zero to zero.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage