theme: minima
title: Newbie Disco
author: Jasmine Zou
email: jasmine.zou22@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  MLOps/Machine Learning/Data
# social links
github_username:  tongz22 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
